[mypy]
python_version = 3.10
ignore_missing_imports = True
follow_imports = skip
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
disable_error_code = no-redef
show_error_codes = True
pretty = True

[mypy-scripts.services.conversion_service]
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-scripts.services.detection_service]
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-scripts.services.logging_service]
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-main]
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-scripts.config]
disallow_untyped_defs = True
check_untyped_defs = True
